name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 14 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - run: export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
      - run: export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - run: aws s3 sync dist/ s3://constshc19at-s3bucket-12o9e6sez9ycn --region "us-east-1"
      - run: aws s3 sync dist/ s3://constshc19at-s3bucket-12o9e6sez9ycn --region "us-east-1" --delete
